###########################################################################
#                                                                         #
#   Realistic Survival Plugin   MC 1.17 - 1.20                            #
#   Version 1.2.8-DEV-0       Made by: Val_Mobile                       #
#                                                                         #
###########################################################################


##############################
#          Messages          #
##############################

RegisteredEnchant: "&7Registered &e%ENCHANT% &7enchant!"                                                            # All internal placeholders: %ENCHANT%
Integration: "&fDetected &e%PLUGIN%&f. Enabling integration!"                                                       # All internal placeholders: %PLUGIN%
CorrectVersion:
  - "&fYou are running the latest version"
OutdatedVersion:
  - "&cYou are running on an outdated version"
  - "&cUpdate to receive the latest features! https://www.spigotmc.org/resources/realistic-survival-1-17-hardcore-modded-experience.93795/history"
DeveloperBuildVersion:
  - "&eYou are running on a developer build"
  - "&eNote that there might be bugs or glitches! Please report any bugs, issues, or glitches"
  - "&ein the plugin support Discord server: https://discord.gg/mMt3f4usqK"

#######################################
#          Gameplay Features          #
#######################################

# Enable and disable features to your liking
# Set a feature to "false" to disable and "true" to enable
# Resource pack is disabled by default to allow for integration of it into
# your own custom server pack if needed
# NOTE: You must restart the server after enabling or disabling any feature
ResourcePack:
  Enabled: true
  # If you upgrade to newer versions, the URL will need to be manually updated to the newest one,
  # which can be found in the Discord server: https://discord.gg/mMt3f4usqK
  Url: "https://www.dropbox.com/scl/fi/5ggc7t20bfxmrzsbb1kok/Realistic-Survival-RP-1.2.8-DEV-0.zip?rlkey=55llpn4zj146usfmm8okf1ier&dl=1"

AutomaticallyEnableWorlds: true   # Will automatically enable modules for newly added worlds; if set to false, automatically disables modules for newly added worlds
AutoUpdateConfig: true            # If set to true, will automatically update config; note that this may cause issues with porting across large updates

NoTreePunching:
  Enabled: true
  Worlds:
    world: true
    world_nether: true
    world_the_end: true
Baubles:
  Enabled: true
  Worlds:
    world: true
    world_nether: true
    world_the_end: true
SpartanWeaponry:
  Enabled: true
  Worlds:
    world: true
    world_nether: true
    world_the_end: true
SpartanandFire:
  Enabled: true # Spartan Weaponry and Ice and Fire must be set to true if enabled
  Worlds:
    world: true
    world_nether: true
    world_the_end: true
IceandFire:
  Enabled: true
  Worlds:
    world: true
    world_nether: true
    world_the_end: true
ToughAsNails:
  Enabled: true
  Worlds:
    world: true
    world_nether: true
    world_the_end: true

####################################
#          Miscellaneous           #
####################################

BStats: true             # Do you want non-confidential server data to be recorded for my use?
ConfigId: "1.2.8-DEV-0"  # Used for config syncing purposes, do NOT edit